name: Lint
on:
  workflow_dispatch: {}
  workflow_call: {}

permissions:
  contents: read

jobs:
  golangci:
    name: GolangCI Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false

      - name: Run Golang CI Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52.2
          skip-cache: true
          skip-pkg-cache: true
          skip-build-cache: true