# Workflow Name
name: Go Tests

# Workflow Triggers
on:
  # Triggered on push to the main and develop branches
  push:
    branches: 
      - main
      - develop
    
   # Triggered on manual dispatch
  workflow_dispatch:

# Workflow Jobs
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    # Checkout Git Repository
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    # Setup Go on runner
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    
    # Run Go tests
    - name: Run Tests
      run: go test -v ./...
