name: Test
on:
  workflow_dispatch: {}
  workflow_call: {}

permissions:
  contents: read

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Go 1.22
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          cache: false

      - name: Run Golang Tests
        run: go test ./... -v -race
